# Generated by Django 6.0.6 on 2026-06-18 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("costo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.CharField(default="activo", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=50)),
                ("apellidos", models.CharField(max_length=50)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contrasena", models.CharField(max_length=255)),
                ("numero_telefono", models.CharField(max_length=15)),
                ("fecha_nacimiento", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Citas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("especialista", models.CharField(max_length=100)),
                ("estado", models.CharField(default="pendiente", max_length=20)),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="citas.servicios",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="citas.usuarios"
                    ),
                ),
            ],
        ),
    ]
