# Generated by Django 6.0.6 on 2026-06-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citas",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("confirmada", "Confirmada"),
                    ("cancelada", "Cancelada"),
                    ("completado", "Completado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
